CREATE DATABASE CAFESHOPDB
USE CAFESHOPDB
CREATE TABLE USERS
(
	USERID     INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME   VARCHAR(50)       NOT NULL    UNIQUE,
	PASSWORD   VARCHAR(255)      NOT NULL,
	ROLE       VARCHAR(20)		 NOT NULL CHECK (ROLE IN ('Admin','Staff')),
	ISACTIVE   
);
